#!/bin/bash
echo "=== 检查 TikTok dylib 日志 ==="
echo ""
echo "请在设备上执行以下命令："
echo ""
echo "1. 查看系统日志（实时）："
echo "   log stream --predicate 'processImagePath contains \"TikTok\"' --level debug"
echo ""
echo "2. 或者查看最近的 TikTok 日志："
echo "   log show --predicate 'processImagePath contains \"TikTok\"' --last 5m | grep -i 'profile\|user\|777777'"
echo ""
echo "3. 检查是否有 dylib 注入："
echo "   log show --predicate 'processImagePath contains \"TikTok\"' --last 5m | grep -i 'TKCap\|dylib'"
echo ""
echo "=== 或者，如果你能访问设备文件系统 ==="
echo ""
echo "4. 查看 TikTok 沙盒内的临时文件："
echo "   find /var/mobile/Containers/Data/Application/*/tmp/ -name '*tiktok*' -o -name '*profile*' 2>/dev/null"
echo ""
